FROM node:24-alpine
WORKDIR /app

# We only need dependencies for development that is stored in its own volume
# Source files are mounted from host machine without node_modules - avoiding any permissions issues
COPY package*.json .
RUN npm ci

EXPOSE 3000
CMD ["sh", "-c", ": \"${API_BASE_URL:?API_BASE_URL environment variable is required}\" && npm run start -- --port 3000 --host 0.0.0.0 --define __API_BASE_URL__=\"'${API_BASE_URL}'\""]
