services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${APP_API_BASE_URL?}
    networks:
      - api-gateway
    labels:
      traefik.enable: true
      traefik.docker.network: spotlite-api-gateway
      traefik.http.routers.frontend.rule: PathPrefix(`/`)
      traefik.http.services.frontend.loadbalancer.server.port: '8080'
networks:
  api-gateway:
    name: spotlite-api-gateway
