services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api-gateway
    labels:
      traefik.enable: true
      traefik.docker.network: api-gateway
      traefik.http.routers.frontend.rule: PathPrefix(`/`)
      traefik.http.services.frontend.loadbalancer.server.port: 80

networks:
  api-gateway: