# Extra modications for development environment

services:
  api-gateway:
    ports:
      - "${APP_GATEWAY_DASHBOARD_PORT}:8080"
    volumes:
      - ./api-gateway/traefik.dev.yml:/etc/traefik/traefik.yml:ro
  # Mailhog is a local SMTP server for testing email sending
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI Dashbaord
    networks:
      # We'll keep mailhog in the api-gateway network.
      # so services that use it can access it.
      # In production, this will be its own accessible service, likely external.
      - api-gateway

networks:
  api-gateway:
