name: spotlite

services:
  api-gateway:
    image: traefik:v3
    ports:
      - ${APP_HTTP_PORT?See README.md "Setup" section}:80
      - ${APP_HTTPS_PORT?}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./api-gateway/traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - ./api-gateway/dynamic:/etc/traefik/dynamic:ro
    networks:
      - api-gateway
    environment:
      OTEL_PROPAGATORS: tracecontext,baggage

  otel-collector: # Observability
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./api-gateway/otelcol.yml:/etc/otelcol/config.yaml:ro
    networks:
      - api-gateway

  nats:
    image: nats:2.12.4
    networks:
      - api-gateway
    volumes:
      - nats-data:/data

networks:
  api-gateway:
    name: spotlite-api-gateway

volumes:
  nats-data:

include:
  - frontend/docker-compose.yml
  - user-service/docker-compose.yml
  - content-service/docker-compose.yml
  - notification-service/docker-compose.yml
  - subscription-service/docker-compose.yml
  - rating-service/docker-compose.yml
  # - recommendation-service/docker-compose.yml
  # - analytic-service/docker-compose.yml
