# Extra modications for development environment.
# This file is automatically merged into `docker-compose.yml` by Docker when no `-f` flag is provided.

services:
  api-gateway:
    ports:
      - 8080:8080
    volumes:
      - ./api-gateway/traefik.dev.yml:/etc/traefik/traefik.yml:ro

  # Override collector config for development
  otel-collector:
    volumes:
      - ./api-gateway/otelcol.dev.yml:/etc/otelcol/config.yaml:ro

  # Jaeger for tracing visualization
  jaeger:
    image: jaegertracing/all-in-one:1.75.0
    labels:
      traefik.enable: true
      traefik.docker.network: api-gateway
      traefik.http.routers.jaeger.rule: PathPrefix(`/dev/jaeger`)
      traefik.http.middlewares.jaeger-strip-prefix.stripprefix.prefixes: /dev/jaeger
      traefik.http.middlewares.jaeger-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.jaeger.loadbalancer.server.port: "16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      QUERY_BASE_PATH: /dev/jaeger
    networks:
      - api-gateway

  # Mailhog is a local SMTP server for testing email sending
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # Web UI Dashbaord
    networks:
      # We'll keep mailhog in the api-gateway network
      # so services that use it can access it.
      # In production, this will be its own accessible service, likely external.
      - api-gateway

  # KeyGen represents a service which generates keys that will be used in jwt signing and validation,
  key-gen:
    image: alpine/openssl
    volumes:
      - keys:/run/keys
    # a bash script which checks if the private key already exists in the keys directory and creates
    # public and private keys if needed,
    entrypoint: >
      sh -c "
        if [ ! -f /run/keys/private.pem ]; then
          echo 'Generating RSA keys...' &&
          openssl genrsa -out /run/keys/private.pem 2048 &&
          openssl rsa -in /run/keys/private.pem -pubout > /run/keys/public.pem &&
          chmod 644 /run/keys/private.pem /run/keys/public.pem;
        else
          echo 'Keys already exist, skipping generation.';
        fi"

  # --- Frontend ---
  # For hot reload

  frontend:
    command: npm run start -- --host 0.0.0.0 --port 3000
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    labels:
      traefik.http.services.frontend.loadbalancer.server.port: "3000"
    volumes:
      - ./frontend/:/app
      # keep node_modules in a separate volume, out of the bind mount
      # this ensures that node_modules folder does not break permissions by Docker
      # and quicker polling for source files
      - frontend-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # reliable file watching on Docker for Win/Mac
      - NG_CLI_ANALYTICS=false # disable telemetry

  # --- User Service ---
  # For local development

  # in the development environment we want the user service to depend on the key-gen, because
  # without it JWTs can't be signed and validated. Also, we are defining volumes and env vars.
  # which the user service will need only in local dev. environment
  user-service:
    volumes:
      - keys:/run/keys:ro
    environment:
      JWT_PRIVATE_KEY_PATH: /run/keys/private.pem
      JWT_PUBLIC_KEY_PATH: /run/keys/public.pem
      APP_JWT_SECRET: "some-secret-key"
    depends_on:
      key-gen:
        condition: service_completed_successfully

  user-mongodb:
    ports:
      - 3101:27017 # expose MongoDB port

  user-mongo-express: # MongoDB GUI
    image: mongo-express:1
    labels:
      traefik.enable: true
      traefik.docker.network: api-gateway
      traefik.http.routers.user-mongo-express.rule: PathPrefix(`/dev/user-service`)
      traefik.http.middlewares.user-mongo-express-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.user-mongo-express.loadbalancer.server.port: "8081"
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_SITE_BASEURL: /dev/user-service
      ME_CONFIG_MONGODB_URL: mongodb://${SRV_USER_MONGO_ROOT_USERNAME}:${SRV_USER_MONGO_ROOT_PASSWORD}@user-mongodb:27017/?authSource=admin
    depends_on:
      user-mongodb:
        condition: service_healthy
    networks:
      - api-gateway
      - user-internal

volumes:
  frontend-node-modules:
  keys:

networks:
  api-gateway:
  user-internal:
