# Extra modications for development environment.
# This file is automatically merged into `docker-compose.yml` by Docker when no `-f` flag is provided.

services:
  api-gateway:
    ports:
      - 8080:8080
    volumes:
      - ./api-gateway/traefik.dev.yml:/etc/traefik/traefik.yml:ro

  nats:
    command: "-js -m 8222"
    ports:
      - "${NATS_MONITOR_PORT?}:8222" # NATS performance monitoring
      - "${NATS_CLIENT_PORT?}:4222" # client port
    volumes:
      - nats-data:/data

  nui:
    image: ghcr.io/nats-nui/nui:0.9.1
    environment:
      - NATS_URL=nats://nats:4222
    labels:
      traefik.enable: true
      traefik.http.routers.nui.rule: PathPrefix(`/dev/nui`)
      traefik.http.middlewares.nui-strip-prefix.stripprefix.prefixes: /dev/nui
      traefik.http.middlewares.nui-strip-prefix.stripprefix.forceslash: false
      traefik.http.routers.nui.middlewares: nui-strip-prefix
      traefik.http.services.nui.loadbalancer.server.port: "31311"
    networks:
      - api-gateway
    depends_on:
      - nats

  # Override collector config for development
  otel-collector:
    volumes:
      - ./api-gateway/otelcol.dev.yml:/etc/otelcol/config.yaml:ro

  # Jaeger for tracing visualization
  jaeger:
    image: jaegertracing/all-in-one:1.75.0
    labels:
      traefik.enable: true
      traefik.docker.network: spotlite-api-gateway
      traefik.http.routers.jaeger.rule: PathPrefix(`/dev/jaeger`)
      traefik.http.middlewares.jaeger-strip-prefix.stripprefix.prefixes: /dev/jaeger
      traefik.http.middlewares.jaeger-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.jaeger.loadbalancer.server.port: "16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      QUERY_BASE_PATH: /dev/jaeger
    networks:
      - api-gateway

  # Mailhog is a local SMTP server for testing email sending
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # Web UI Dashbaord
    networks:
      # We'll keep mailhog in the api-gateway network
      # so services that use it can access it.
      # In production, this will be its own accessible service, likely external.
      - api-gateway

  # KeyGen represents a service which generates keys that will be used in jwt signing and validation,
  key-gen:
    image: alpine/openssl
    volumes:
      - keys:/run/keys
    # a bash script which checks if the private key already exists in the keys directory and creates
    # public and private keys if needed,
    entrypoint: >
      sh -c "
        if [ ! -f /run/keys/private.pem ]; then
          echo 'Generating RSA keys...' &&
          openssl genrsa -out /run/keys/private.pem 2048 &&
          openssl rsa -in /run/keys/private.pem -pubout > /run/keys/public.pem &&
          chmod 644 /run/keys/private.pem /run/keys/public.pem;
        else
          echo 'Keys already exist, skipping generation.';
        fi"

  # --- Frontend ---
  # For hot reload

  frontend:
    command: npm run start -- --host 0.0.0.0 --port 3000
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    labels:
      traefik.http.services.frontend.loadbalancer.server.port: "3000"
    volumes:
      - ./frontend/:/app
      # keep node_modules in a separate volume, out of the bind mount
      # this ensures that node_modules folder does not break permissions by Docker
      # and quicker polling for source files
      - frontend-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # reliable file watching on Docker for Win/Mac
      - NG_CLI_ANALYTICS=false # disable telemetry

  # --- User Service ---

  # in the development environment we want the user service to depend on the key-gen, because
  # without it JWTs can't be signed and validated. Also, we are defining volumes and env vars.
  # which the user service will need only in local dev. environment
  user-service:
    volumes:
      - keys:/run/keys:ro
    environment:
      JWT_PRIVATE_KEY_PATH: /run/keys/private.pem
      JWT_PUBLIC_KEY_PATH: /run/keys/public.pem
    depends_on:
      key-gen:
        condition: service_completed_successfully

  user-mongodb:
    ports:
      - 3101:27017 # expose MongoDB port

  user-mongo-express: # MongoDB GUI
    image: mongo-express:1
    labels:
      traefik.enable: true
      traefik.docker.network: spotlite-api-gateway
      traefik.http.routers.user-mongo-express.rule: PathPrefix(`/dev/user-service`)
      traefik.http.routers.user-mongo-express.middlewares: user-mongo-express-strip-prefix
      traefik.http.middlewares.user-mongo-express-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.user-mongo-express.loadbalancer.server.port: "8081"
      traefik.http.services.user-mongo-express.loadbalancer.healthcheck.path: /dev/user-service
      traefik.http.services.user-mongo-express.loadbalancer.healthcheck.interval: 5s
      traefik.http.services.user-mongo-express.loadbalancer.healthcheck.timeout: 2s
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_SITE_BASEURL: /dev/user-service
      ME_CONFIG_MONGODB_URL: mongodb://${SRV_USER_MONGO_ROOT_USERNAME}:${SRV_USER_MONGO_ROOT_PASSWORD}@user-mongodb:27017/?authSource=admin
    depends_on:
      user-mongodb:
        condition: service_healthy
    networks:
      - api-gateway
      - user-internal

  # --- Content Service ---
  content-mongodb:
    ports:
      - 3102:27017 # expose MongoDB port

  content-mongo-express: # MongoDB GUI
    image: mongo-express:1
    labels:
      traefik.enable: true
      traefik.docker.network: spotlite-api-gateway
      traefik.http.routers.content-mongo-express.rule: PathPrefix(`/dev/content-service`)
      traefik.http.routers.content-mongo-express.middlewares: content-mongo-express-strip-prefix
      traefik.http.middlewares.content-mongo-express-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.content-mongo-express.loadbalancer.server.port: "8081"
      traefik.http.services.content-mongo-express.loadbalancer.healthcheck.path: /dev/content-service
      traefik.http.services.content-mongo-express.loadbalancer.healthcheck.interval: 5s
      traefik.http.services.content-mongo-express.loadbalancer.healthcheck.timeout: 2s
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_SITE_BASEURL: /dev/content-service
      ME_CONFIG_MONGODB_URL: mongodb://${SRV_CONTENT_MONGO_ROOT_USERNAME}:${SRV_CONTENT_MONGO_ROOT_PASSWORD}@content-mongodb:27017/?authSource=admin
    depends_on:
      content-mongodb:
        condition: service_healthy
    networks:
      - api-gateway
      - content-internal

  # --- Notification Service ---
  notification-service:
    volumes:
      - keys:/run/keys:ro
    environment:
      JWT_PRIVATE_KEY_PATH: /run/keys/private.pem
      JWT_PUBLIC_KEY_PATH: /run/keys/public.pem
    depends_on:
      key-gen:
        condition: service_completed_successfully

  notification-cassandra:
    ports:
      - "${CASSANDRA_PORT}:9042"

  # --- Subscription Service ---
  subscription-service:
    volumes:
      - keys:/run/keys:ro
    environment:
      JWT_PUBLIC_KEY_PATH: /run/keys/public.pem
    depends_on:
      key-gen:
        condition: service_completed_successfully

  subscription-mongodb:
    ports:
      - 3103:27017

  subscription-mongo-express: # MongoDB GUI
    image: mongo-express:1
    labels:
      traefik.enable: true
      traefik.docker.network: spotlite-api-gateway
      traefik.http.routers.subscription-mongo-express.rule: PathPrefix(`/dev/subscription-service`)
      traefik.http.routers.subscription-mongo-express.middlewares: subscription-mongo-express-strip-prefix
      traefik.http.middlewares.subscription-mongo-express-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.subscription-mongo-express.loadbalancer.server.port: "8081"
      traefik.http.services.subscription-mongo-express.loadbalancer.healthcheck.path: /dev/subscription-service
      traefik.http.services.subscription-mongo-express.loadbalancer.healthcheck.interval: 5s
      traefik.http.services.subscription-mongo-express.loadbalancer.healthcheck.timeout: 2s
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_SITE_BASEURL: /dev/subscription-service
      ME_CONFIG_MONGODB_URL: mongodb://${SRV_SUB_MONGO_ROOT_USERNAME}:${SRV_SUB_MONGO_ROOT_PASSWORD}@subscription-mongodb:27017/?authSource=admin
    depends_on:
      subscription-mongodb:
        condition: service_healthy
    networks:
      - api-gateway
      - subscription-internal

volumes:
  frontend-node-modules:
  keys:
  nats-data:

networks:
  api-gateway:
    name: spotlite-api-gateway
  user-internal:
