# Stage 1 (Build)
FROM golang:1.25.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum /app/
RUN --mount=type=cache,target=/go/pkg/mod \
	--mount=type=cache,target=/root/.cache/go-build \
	go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
	--mount=type=cache,target=/root/.cache/go-build \
	CGO_ENABLED=0 go build \
	-ldflags="-s -w" \
	-v \
	-trimpath \
	-o /app/build.bin \
	main.go

# Stage 2 (Final)
FROM gcr.io/distroless/static:latest

WORKDIR /app

COPY --from=builder /app/build.bin /usr/bin/service

ENTRYPOINT ["/usr/bin/service"]
