// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: common-lib/proto/rating_service/get_song_rating.proto

package rating_service_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetSongRating_GetSongRatingSummary_FullMethodName = "/rating_service.GetSongRating/GetSongRatingSummary"
)

// GetSongRatingClient is the client API for GetSongRating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetSongRatingClient interface {
	GetSongRatingSummary(ctx context.Context, in *SongIDRequest, opts ...grpc.CallOption) (*SongRatingSummaryResponse, error)
}

type getSongRatingClient struct {
	cc grpc.ClientConnInterface
}

func NewGetSongRatingClient(cc grpc.ClientConnInterface) GetSongRatingClient {
	return &getSongRatingClient{cc}
}

func (c *getSongRatingClient) GetSongRatingSummary(ctx context.Context, in *SongIDRequest, opts ...grpc.CallOption) (*SongRatingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SongRatingSummaryResponse)
	err := c.cc.Invoke(ctx, GetSongRating_GetSongRatingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetSongRatingServer is the server API for GetSongRating service.
// All implementations must embed UnimplementedGetSongRatingServer
// for forward compatibility.
type GetSongRatingServer interface {
	GetSongRatingSummary(context.Context, *SongIDRequest) (*SongRatingSummaryResponse, error)
	mustEmbedUnimplementedGetSongRatingServer()
}

// UnimplementedGetSongRatingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetSongRatingServer struct{}

func (UnimplementedGetSongRatingServer) GetSongRatingSummary(context.Context, *SongIDRequest) (*SongRatingSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSongRatingSummary not implemented")
}
func (UnimplementedGetSongRatingServer) mustEmbedUnimplementedGetSongRatingServer() {}
func (UnimplementedGetSongRatingServer) testEmbeddedByValue()                       {}

// UnsafeGetSongRatingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetSongRatingServer will
// result in compilation errors.
type UnsafeGetSongRatingServer interface {
	mustEmbedUnimplementedGetSongRatingServer()
}

func RegisterGetSongRatingServer(s grpc.ServiceRegistrar, srv GetSongRatingServer) {
	// If the following call pancis, it indicates UnimplementedGetSongRatingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetSongRating_ServiceDesc, srv)
}

func _GetSongRating_GetSongRatingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetSongRatingServer).GetSongRatingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetSongRating_GetSongRatingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetSongRatingServer).GetSongRatingSummary(ctx, req.(*SongIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetSongRating_ServiceDesc is the grpc.ServiceDesc for GetSongRating service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetSongRating_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rating_service.GetSongRating",
	HandlerType: (*GetSongRatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSongRatingSummary",
			Handler:    _GetSongRating_GetSongRatingSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common-lib/proto/rating_service/get_song_rating.proto",
}
