// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.33.1
// source: common-lib/proto/rating_service/get_song_rating.proto

package rating_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SongIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SongId        string                 `protobuf:"bytes,1,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongIDRequest) Reset() {
	*x = SongIDRequest{}
	mi := &file_common_lib_proto_rating_service_get_song_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongIDRequest) ProtoMessage() {}

func (x *SongIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_lib_proto_rating_service_get_song_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongIDRequest.ProtoReflect.Descriptor instead.
func (*SongIDRequest) Descriptor() ([]byte, []int) {
	return file_common_lib_proto_rating_service_get_song_rating_proto_rawDescGZIP(), []int{0}
}

func (x *SongIDRequest) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

type SongRatingSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float64                `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SongRatingSummaryResponse) Reset() {
	*x = SongRatingSummaryResponse{}
	mi := &file_common_lib_proto_rating_service_get_song_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SongRatingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SongRatingSummaryResponse) ProtoMessage() {}

func (x *SongRatingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_lib_proto_rating_service_get_song_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SongRatingSummaryResponse.ProtoReflect.Descriptor instead.
func (*SongRatingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_common_lib_proto_rating_service_get_song_rating_proto_rawDescGZIP(), []int{1}
}

func (x *SongRatingSummaryResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *SongRatingSummaryResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_common_lib_proto_rating_service_get_song_rating_proto protoreflect.FileDescriptor

var file_common_lib_proto_rating_service_get_song_rating_proto_rawDesc = string([]byte{
	0x0a, 0x35, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x6f, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x28, 0x0a, 0x0d, 0x53, 0x6f, 0x6e, 0x67, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6f, 0x6e, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x6e, 0x67, 0x49,
	0x64, 0x22, 0x4b, 0x0a, 0x19, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x71,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x60, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x61, 0x6e, 0x6a, 0x6d, 0x61, 0x6c, 0x69, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x6c, 0x69, 0x74,
	0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x3b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_common_lib_proto_rating_service_get_song_rating_proto_rawDescOnce sync.Once
	file_common_lib_proto_rating_service_get_song_rating_proto_rawDescData []byte
)

func file_common_lib_proto_rating_service_get_song_rating_proto_rawDescGZIP() []byte {
	file_common_lib_proto_rating_service_get_song_rating_proto_rawDescOnce.Do(func() {
		file_common_lib_proto_rating_service_get_song_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_lib_proto_rating_service_get_song_rating_proto_rawDesc), len(file_common_lib_proto_rating_service_get_song_rating_proto_rawDesc)))
	})
	return file_common_lib_proto_rating_service_get_song_rating_proto_rawDescData
}

var file_common_lib_proto_rating_service_get_song_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_lib_proto_rating_service_get_song_rating_proto_goTypes = []any{
	(*SongIDRequest)(nil),             // 0: rating_service.SongIDRequest
	(*SongRatingSummaryResponse)(nil), // 1: rating_service.SongRatingSummaryResponse
}
var file_common_lib_proto_rating_service_get_song_rating_proto_depIdxs = []int32{
	0, // 0: rating_service.GetSongRating.GetSongRatingSummary:input_type -> rating_service.SongIDRequest
	1, // 1: rating_service.GetSongRating.GetSongRatingSummary:output_type -> rating_service.SongRatingSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_lib_proto_rating_service_get_song_rating_proto_init() }
func file_common_lib_proto_rating_service_get_song_rating_proto_init() {
	if File_common_lib_proto_rating_service_get_song_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_lib_proto_rating_service_get_song_rating_proto_rawDesc), len(file_common_lib_proto_rating_service_get_song_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_lib_proto_rating_service_get_song_rating_proto_goTypes,
		DependencyIndexes: file_common_lib_proto_rating_service_get_song_rating_proto_depIdxs,
		MessageInfos:      file_common_lib_proto_rating_service_get_song_rating_proto_msgTypes,
	}.Build()
	File_common_lib_proto_rating_service_get_song_rating_proto = out.File
	file_common_lib_proto_rating_service_get_song_rating_proto_goTypes = nil
	file_common_lib_proto_rating_service_get_song_rating_proto_depIdxs = nil
}
