package repositories

import (
	"context"
	"errors"
	"fmt"

	"github.com/vanjmali/spotlite/analytics-service/entities"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

var ErrInvalidEvent = errors.New("invalid event data")

// EventStoreRepository provides data access helpers for immutable event log.
// It implements the write model of the Event Sourcing pattern, persisting all domain events
// to an append-only log in MongoDB.
type EventStoreRepository struct {
	DbName   string
	CollName string
	Client   *mongo.Client
}

func (r *EventStoreRepository) getCollection() *mongo.Collection {
	return r.Client.Database(r.DbName).Collection(r.CollName)
}

// NewEventStoreRepository constructs an EventStoreRepository for the given database and collection.
func NewEventStoreRepository(dbName string, collName string, c *mongo.Client) *EventStoreRepository {
	r := EventStoreRepository{Client: c, DbName: dbName, CollName: collName}
	return &r
}

// EnsureIndexes creates indexes required for efficient event queries per specification.
// Indexes support the following query patterns:
// - Find events by user and event type for read model projection
// - Time-range queries on events
// - Prevent duplicate events with unique constraint
func (r *EventStoreRepository) EnsureIndexes(ctx context.Context) error {
	c := r.getCollection()

	indexModels := []mongo.IndexModel{
		{
			Keys: bson.D{
				{Key: "user_id", Value: 1},
				{Key: "event_type", Value: 1},
			},
			Options: options.Index().SetName("event_store_user_id_event_type_idx"),
		},
		{
			Keys:    bson.D{{Key: "timestamp", Value: 1}},
			Options: options.Index().SetName("event_store_timestamp_idx"),
		},
	}

	_, err := c.Indexes().CreateMany(ctx, indexModels)
	if err != nil {
		return fmt.Errorf("failed to create event store indexes: %w", err)
	}

	return nil
}

// StoreEvent persists an immutable event to the event log.
// Each event is written once and never modified, maintaining the append-only log invariant.
// The event ID is generated by MongoDB (_id field) for uniqueness.
func (r *EventStoreRepository) StoreEvent(ctx context.Context, event *entities.Event) error {
	if event == nil {
		return ErrInvalidEvent
	}

	c := r.getCollection()

	_, err := c.InsertOne(ctx, event)
	if err != nil {
		return fmt.Errorf("failed to store event: %w", err)
	}

	return nil
}
