// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: common-lib/proto/content_service/content_checker.proto

package content_service_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentChecker_CheckGenreExistence_FullMethodName  = "/content_service.ContentChecker/CheckGenreExistence"
	ContentChecker_CheckArtistExistence_FullMethodName = "/content_service.ContentChecker/CheckArtistExistence"
)

// ContentCheckerClient is the client API for ContentChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentCheckerClient interface {
	CheckGenreExistence(ctx context.Context, in *CheckIdRequest, opts ...grpc.CallOption) (*ExistenceResponse, error)
	CheckArtistExistence(ctx context.Context, in *CheckIdRequest, opts ...grpc.CallOption) (*ExistenceResponse, error)
}

type contentCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewContentCheckerClient(cc grpc.ClientConnInterface) ContentCheckerClient {
	return &contentCheckerClient{cc}
}

func (c *contentCheckerClient) CheckGenreExistence(ctx context.Context, in *CheckIdRequest, opts ...grpc.CallOption) (*ExistenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistenceResponse)
	err := c.cc.Invoke(ctx, ContentChecker_CheckGenreExistence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentCheckerClient) CheckArtistExistence(ctx context.Context, in *CheckIdRequest, opts ...grpc.CallOption) (*ExistenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistenceResponse)
	err := c.cc.Invoke(ctx, ContentChecker_CheckArtistExistence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentCheckerServer is the server API for ContentChecker service.
// All implementations must embed UnimplementedContentCheckerServer
// for forward compatibility.
type ContentCheckerServer interface {
	CheckGenreExistence(context.Context, *CheckIdRequest) (*ExistenceResponse, error)
	CheckArtistExistence(context.Context, *CheckIdRequest) (*ExistenceResponse, error)
	mustEmbedUnimplementedContentCheckerServer()
}

// UnimplementedContentCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentCheckerServer struct{}

func (UnimplementedContentCheckerServer) CheckGenreExistence(context.Context, *CheckIdRequest) (*ExistenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckGenreExistence not implemented")
}
func (UnimplementedContentCheckerServer) CheckArtistExistence(context.Context, *CheckIdRequest) (*ExistenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckArtistExistence not implemented")
}
func (UnimplementedContentCheckerServer) mustEmbedUnimplementedContentCheckerServer() {}
func (UnimplementedContentCheckerServer) testEmbeddedByValue()                        {}

// UnsafeContentCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentCheckerServer will
// result in compilation errors.
type UnsafeContentCheckerServer interface {
	mustEmbedUnimplementedContentCheckerServer()
}

func RegisterContentCheckerServer(s grpc.ServiceRegistrar, srv ContentCheckerServer) {
	// If the following call panics, it indicates UnimplementedContentCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentChecker_ServiceDesc, srv)
}

func _ContentChecker_CheckGenreExistence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCheckerServer).CheckGenreExistence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentChecker_CheckGenreExistence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCheckerServer).CheckGenreExistence(ctx, req.(*CheckIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentChecker_CheckArtistExistence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentCheckerServer).CheckArtistExistence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentChecker_CheckArtistExistence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentCheckerServer).CheckArtistExistence(ctx, req.(*CheckIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentChecker_ServiceDesc is the grpc.ServiceDesc for ContentChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content_service.ContentChecker",
	HandlerType: (*ContentCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckGenreExistence",
			Handler:    _ContentChecker_CheckGenreExistence_Handler,
		},
		{
			MethodName: "CheckArtistExistence",
			Handler:    _ContentChecker_CheckArtistExistence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common-lib/proto/content_service/content_checker.proto",
}
