// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: common-lib/proto/content_service/content_checker.proto

package content_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIdRequest) Reset() {
	*x = CheckIdRequest{}
	mi := &file_common_lib_proto_content_service_content_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIdRequest) ProtoMessage() {}

func (x *CheckIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_lib_proto_content_service_content_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIdRequest.ProtoReflect.Descriptor instead.
func (*CheckIdRequest) Descriptor() ([]byte, []int) {
	return file_common_lib_proto_content_service_content_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckIdRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type ExistenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistenceResponse) Reset() {
	*x = ExistenceResponse{}
	mi := &file_common_lib_proto_content_service_content_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistenceResponse) ProtoMessage() {}

func (x *ExistenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_lib_proto_content_service_content_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistenceResponse.ProtoReflect.Descriptor instead.
func (*ExistenceResponse) Descriptor() ([]byte, []int) {
	return file_common_lib_proto_content_service_content_checker_proto_rawDescGZIP(), []int{1}
}

func (x *ExistenceResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_common_lib_proto_content_service_content_checker_proto protoreflect.FileDescriptor

const file_common_lib_proto_content_service_content_checker_proto_rawDesc = "" +
	"\n" +
	"6common-lib/proto/content_service/content_checker.proto\x12\x0fcontent_service\"-\n" +
	"\x0eCheckIdRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"+\n" +
	"\x11ExistenceResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xc9\x01\n" +
	"\x0eContentChecker\x12Z\n" +
	"\x13CheckGenreExistence\x12\x1f.content_service.CheckIdRequest\x1a\".content_service.ExistenceResponse\x12[\n" +
	"\x14CheckArtistExistence\x12\x1f.content_service.CheckIdRequest\x1a\".content_service.ExistenceResponseBRZPgithub.com/vanjmali/spotlite/common-lib/proto/content_service;content_service_pbb\x06proto3"

var (
	file_common_lib_proto_content_service_content_checker_proto_rawDescOnce sync.Once
	file_common_lib_proto_content_service_content_checker_proto_rawDescData []byte
)

func file_common_lib_proto_content_service_content_checker_proto_rawDescGZIP() []byte {
	file_common_lib_proto_content_service_content_checker_proto_rawDescOnce.Do(func() {
		file_common_lib_proto_content_service_content_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_lib_proto_content_service_content_checker_proto_rawDesc), len(file_common_lib_proto_content_service_content_checker_proto_rawDesc)))
	})
	return file_common_lib_proto_content_service_content_checker_proto_rawDescData
}

var file_common_lib_proto_content_service_content_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_lib_proto_content_service_content_checker_proto_goTypes = []any{
	(*CheckIdRequest)(nil),    // 0: content_service.CheckIdRequest
	(*ExistenceResponse)(nil), // 1: content_service.ExistenceResponse
}
var file_common_lib_proto_content_service_content_checker_proto_depIdxs = []int32{
	0, // 0: content_service.ContentChecker.CheckGenreExistence:input_type -> content_service.CheckIdRequest
	0, // 1: content_service.ContentChecker.CheckArtistExistence:input_type -> content_service.CheckIdRequest
	1, // 2: content_service.ContentChecker.CheckGenreExistence:output_type -> content_service.ExistenceResponse
	1, // 3: content_service.ContentChecker.CheckArtistExistence:output_type -> content_service.ExistenceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_lib_proto_content_service_content_checker_proto_init() }
func file_common_lib_proto_content_service_content_checker_proto_init() {
	if File_common_lib_proto_content_service_content_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_lib_proto_content_service_content_checker_proto_rawDesc), len(file_common_lib_proto_content_service_content_checker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_lib_proto_content_service_content_checker_proto_goTypes,
		DependencyIndexes: file_common_lib_proto_content_service_content_checker_proto_depIdxs,
		MessageInfos:      file_common_lib_proto_content_service_content_checker_proto_msgTypes,
	}.Build()
	File_common_lib_proto_content_service_content_checker_proto = out.File
	file_common_lib_proto_content_service_content_checker_proto_goTypes = nil
	file_common_lib_proto_content_service_content_checker_proto_depIdxs = nil
}
