// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/content_service/get_content_entity.proto

package content_service_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetContentEntity_GetArtist_FullMethodName = "/content_service.GetContentEntity/GetArtist"
	GetContentEntity_GetGenre_FullMethodName  = "/content_service.GetContentEntity/GetGenre"
)

// GetContentEntityClient is the client API for GetContentEntity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetContentEntityClient interface {
	GetArtist(ctx context.Context, in *EntityIDRequest, opts ...grpc.CallOption) (*GetContentEntityResponse, error)
	GetGenre(ctx context.Context, in *EntityIDRequest, opts ...grpc.CallOption) (*GetContentEntityResponse, error)
}

type getContentEntityClient struct {
	cc grpc.ClientConnInterface
}

func NewGetContentEntityClient(cc grpc.ClientConnInterface) GetContentEntityClient {
	return &getContentEntityClient{cc}
}

func (c *getContentEntityClient) GetArtist(ctx context.Context, in *EntityIDRequest, opts ...grpc.CallOption) (*GetContentEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentEntityResponse)
	err := c.cc.Invoke(ctx, GetContentEntity_GetArtist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getContentEntityClient) GetGenre(ctx context.Context, in *EntityIDRequest, opts ...grpc.CallOption) (*GetContentEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentEntityResponse)
	err := c.cc.Invoke(ctx, GetContentEntity_GetGenre_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetContentEntityServer is the server API for GetContentEntity service.
// All implementations must embed UnimplementedGetContentEntityServer
// for forward compatibility.
type GetContentEntityServer interface {
	GetArtist(context.Context, *EntityIDRequest) (*GetContentEntityResponse, error)
	GetGenre(context.Context, *EntityIDRequest) (*GetContentEntityResponse, error)
	mustEmbedUnimplementedGetContentEntityServer()
}

// UnimplementedGetContentEntityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetContentEntityServer struct{}

func (UnimplementedGetContentEntityServer) GetArtist(context.Context, *EntityIDRequest) (*GetContentEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtist not implemented")
}
func (UnimplementedGetContentEntityServer) GetGenre(context.Context, *EntityIDRequest) (*GetContentEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGenre not implemented")
}
func (UnimplementedGetContentEntityServer) mustEmbedUnimplementedGetContentEntityServer() {}
func (UnimplementedGetContentEntityServer) testEmbeddedByValue()                          {}

// UnsafeGetContentEntityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetContentEntityServer will
// result in compilation errors.
type UnsafeGetContentEntityServer interface {
	mustEmbedUnimplementedGetContentEntityServer()
}

func RegisterGetContentEntityServer(s grpc.ServiceRegistrar, srv GetContentEntityServer) {
	// If the following call panics, it indicates UnimplementedGetContentEntityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetContentEntity_ServiceDesc, srv)
}

func _GetContentEntity_GetArtist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetContentEntityServer).GetArtist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetContentEntity_GetArtist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetContentEntityServer).GetArtist(ctx, req.(*EntityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetContentEntity_GetGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetContentEntityServer).GetGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetContentEntity_GetGenre_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetContentEntityServer).GetGenre(ctx, req.(*EntityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetContentEntity_ServiceDesc is the grpc.ServiceDesc for GetContentEntity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetContentEntity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content_service.GetContentEntity",
	HandlerType: (*GetContentEntityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArtist",
			Handler:    _GetContentEntity_GetArtist_Handler,
		},
		{
			MethodName: "GetGenre",
			Handler:    _GetContentEntity_GetGenre_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/content_service/get_content_entity.proto",
}
