// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: get_content_entity.proto

package content_service_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityIDRequest) Reset() {
	*x = EntityIDRequest{}
	mi := &file_get_content_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityIDRequest) ProtoMessage() {}

func (x *EntityIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_content_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityIDRequest.ProtoReflect.Descriptor instead.
func (*EntityIDRequest) Descriptor() ([]byte, []int) {
	return file_get_content_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EntityIDRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetContentEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentEntityResponse) Reset() {
	*x = GetContentEntityResponse{}
	mi := &file_get_content_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentEntityResponse) ProtoMessage() {}

func (x *GetContentEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_content_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentEntityResponse.ProtoReflect.Descriptor instead.
func (*GetContentEntityResponse) Descriptor() ([]byte, []int) {
	return file_get_content_entity_proto_rawDescGZIP(), []int{1}
}

func (x *GetContentEntityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_get_content_entity_proto protoreflect.FileDescriptor

const file_get_content_entity_proto_rawDesc = "" +
	"\n" +
	"\x18get_content_entity.proto\x12\x0fcontent_service\".\n" +
	"\x0fEntityIDRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\".\n" +
	"\x18GetContentEntityResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x9d\x02\n" +
	"\x10GetContentEntity\x12X\n" +
	"\tGetArtist\x12 .content_service.EntityIDRequest\x1a).content_service.GetContentEntityResponse\x12W\n" +
	"\bGetGenre\x12 .content_service.EntityIDRequest\x1a).content_service.GetContentEntityResponse\x12V\n" +
	"\aGetSong\x12 .content_service.EntityIDRequest\x1a).content_service.GetContentEntityResponseBRZPgithub.com/vanjmali/spotlite/common-lib/proto/content_service;content_service_pbb\x06proto3"

var (
	file_get_content_entity_proto_rawDescOnce sync.Once
	file_get_content_entity_proto_rawDescData []byte
)

func file_get_content_entity_proto_rawDescGZIP() []byte {
	file_get_content_entity_proto_rawDescOnce.Do(func() {
		file_get_content_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_content_entity_proto_rawDesc), len(file_get_content_entity_proto_rawDesc)))
	})
	return file_get_content_entity_proto_rawDescData
}

var file_get_content_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_content_entity_proto_goTypes = []any{
	(*EntityIDRequest)(nil),          // 0: content_service.EntityIDRequest
	(*GetContentEntityResponse)(nil), // 1: content_service.GetContentEntityResponse
}
var file_get_content_entity_proto_depIdxs = []int32{
	0, // 0: content_service.GetContentEntity.GetArtist:input_type -> content_service.EntityIDRequest
	0, // 1: content_service.GetContentEntity.GetGenre:input_type -> content_service.EntityIDRequest
	0, // 2: content_service.GetContentEntity.GetSong:input_type -> content_service.EntityIDRequest
	1, // 3: content_service.GetContentEntity.GetArtist:output_type -> content_service.GetContentEntityResponse
	1, // 4: content_service.GetContentEntity.GetGenre:output_type -> content_service.GetContentEntityResponse
	1, // 5: content_service.GetContentEntity.GetSong:output_type -> content_service.GetContentEntityResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_content_entity_proto_init() }
func file_get_content_entity_proto_init() {
	if File_get_content_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_content_entity_proto_rawDesc), len(file_get_content_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_content_entity_proto_goTypes,
		DependencyIndexes: file_get_content_entity_proto_depIdxs,
		MessageInfos:      file_get_content_entity_proto_msgTypes,
	}.Build()
	File_get_content_entity_proto = out.File
	file_get_content_entity_proto_goTypes = nil
	file_get_content_entity_proto_depIdxs = nil
}
