services:
  user-mongodb:
    ports:
      - ${SRV_USER_MONGO_DEV_PORT}:27017

  user-mongo-express:
    image: mongo-express
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=api-gateway"
      - "traefik.http.routers.user-mongo-express.rule=PathPrefix(`/dev/user-service`)"
      - "traefik.http.middlewares.user-mongo-express-strip-prefix.stripprefix.forceslash=false"
      - "traefik.http.services.user-mongo-express.loadbalancer.server.port=8081"
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_SITE_BASEURL: /dev/user-service
      ME_CONFIG_MONGODB_URL: mongodb://${SRV_USER_MONGO_ROOT_USERNAME}:${SRV_USER_MONGO_ROOT_PASSWORD}@user-mongodb:27017/?authSource=admin
    depends_on:
      user-mongodb:
        condition: service_healthy
    networks:
      - api-gateway
      - user-internal

networks:
  api-gateway:
  user-internal:
