services:
  user-service:
    build:
      context: .
      additional_contexts:
        common-lib: ../common-lib
      dockerfile: ../Dockerfile.microservice
    environment:
      DB_HOST: user-mongodb
      DB_PORT: 27017
      DB_USER: ${SRV_USER_MONGO_USERNAME?}
      DB_PASS: ${SRV_USER_MONGO_PASSWORD?}
      DB_NAME: ${SRV_USER_MONGO_DATABASE?}
      SMTP_HOST: ${SRV_USER_SMTP_HOST?}
      SMTP_PORT: ${SRV_USER_SMTP_PORT?}
      SMTP_USER: ${SRV_USER_SMTP_USERNAME?}
      SMTP_PASS: ${SRV_USER_SMTP_PASSWORD?}
      APP_JWT_SECRET: ${SRV_USER_JWT_SECRET?}
      APP_VERIFICATION_SUCCESS_URL: ${SRV_USER_VERIFICATION_SUCCESS_URL?}
      APP_VERIFICATION_FAILURE_URL: ${SRV_USER_VERIFICATION_FAILURE_URL?}
      APP_LOGIN_OTP_TTL_MINUTES: ${SRV_USER_LOGIN_OTP_TTL_MINUTES?}
      APP_PORT: 3000
    labels:
      traefik.enable: true
      traefik.docker.network: api-gateway
      traefik.http.routers.user-service.rule: PathPrefix(`/api/users`)
      traefik.http.routers.user-service.middlewares: user-service-strip-prefix
      traefik.http.middlewares.user-service-strip-prefix.stripprefix.prefixes: /api/users
      traefik.http.middlewares.user-service-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.user-service.loadbalancer.server.port: 3000
    depends_on:
      user-mongodb:
        condition: service_healthy
    networks:
      - api-gateway
      - user-internal

  user-mongodb:
    image: mongo:8.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SRV_USER_MONGO_ROOT_USERNAME?}
      MONGO_INITDB_ROOT_PASSWORD: ${SRV_USER_MONGO_ROOT_PASSWORD?}
      MONGO_INITDB_DATABASE: ${SRV_USER_MONGO_DATABASE?}
      SRV_USER_MONGO_USERNAME: ${SRV_USER_MONGO_USERNAME?}
      SRV_USER_MONGO_PASSWORD: ${SRV_USER_MONGO_PASSWORD?}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh --username $SRV_USER_MONGO_ROOT_USERNAME --password $SRV_USER_MONGO_ROOT_PASSWORD --authenticationDatabase admin --eval ''db.adminCommand("ping")''',
        ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - user-mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - user-internal

networks:
  # Connects to Traefik
  api-gateway:
  # Creates a private network for this microservice
  user-internal:

volumes:
  user-mongo-data:
