services:
  user-service:
    build:
      context: .
      additional_contexts:
        common-lib: ../common-lib
      dockerfile: ../Dockerfile.microservice
    environment:
      APP_PORT: 3000
      REDIS_ADDR: user-redis:6379
      DB_HOST: user-mongodb
      DB_PORT: 27017
      DB_USER: ${SRV_USER_MONGO_USERNAME?}
      DB_PASS: ${SRV_USER_MONGO_PASSWORD?}
      DB_NAME: ${SRV_USER_MONGO_DATABASE?}
      SMTP_HOST: ${SRV_USER_SMTP_HOST?}
      SMTP_PORT: ${SRV_USER_SMTP_PORT?}
      SMTP_USER: ${SRV_USER_SMTP_USERNAME?}
      SMTP_PASS: ${SRV_USER_SMTP_PASSWORD?}
      MAIL_FROM: ${SRV_USER_MAIL_FROM_ADDRESS?}
      # JWT_PRIVATE_KEY_PATH: /run/keys/private.pem
      # JWT_PUBLIC_KEY_PATH: /run/keys/public.pem
      SRV_USER_VERIFY_URL: ${SRV_USER_VERIFY_URL?}
      SRV_USER_PASSWORD_RESET_URL: ${SRV_USER_PASSWORD_RESET_URL?}
      APP_LOGIN_OTP_TTL_MINUTES: ${SRV_USER_LOGIN_OTP_TTL_MINUTES?}
      APP_REFRESH_COOKIE_NAME: ${SRV_USER_REFRESH_COOKIE_NAME?}
      APP_REFRESH_COOKIE_DOMAIN: ${SRV_USER_REFRESH_COOKIE_DOMAIN}
      APP_REFRESH_COOKIE_SECURE: ${SRV_USER_REFRESH_COOKIE_SECURE?}
      APP_REFRESH_COOKIE_SAMESITE: ${SRV_USER_REFRESH_COOKIE_SAMESITE?}
      LOG_DIR: ${LOG_DIR?}
      LOG_ROTATE_MAX_SIZE_MB: ${LOG_ROTATE_MAX_SIZE_MB?}
      LOG_ROTATE_MAX_BACKUPS: ${LOG_ROTATE_MAX_BACKUPS?}
      LOG_ROTATE_MAX_AGE_DAYS: ${LOG_ROTATE_MAX_AGE_DAYS?}
      LOG_ROTATE_COMPRESS: ${LOG_ROTATE_COMPRESS?}
      NATS_URL: ${NATS_URL?}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
    labels:
      traefik.enable: true
      traefik.docker.network: spotlite-api-gateway
      traefik.http.routers.user-service.rule: PathPrefix(`/api/users`)
      traefik.http.routers.user-service.middlewares: user-service-strip-prefix@docker,rate-limit-global@file
      traefik.http.middlewares.user-service-strip-prefix.stripprefix.prefixes: /api/users
      traefik.http.services.user-service.loadbalancer.server.scheme: https
      traefik.http.middlewares.user-service-strip-prefix.stripprefix.forceslash: false
      traefik.http.services.user-service.loadbalancer.server.port: "3000"
      traefik.http.services.user-service.loadbalancer.healthcheck.path: /healthz
      traefik.http.services.user-service.loadbalancer.healthcheck.interval: 5s
      traefik.http.services.user-service.loadbalancer.healthcheck.timeout: 2s
      traefik.http.routers.user-service.entrypoints: websecure
      traefik.http.routers.user-service.tls: true
    depends_on:
      user-mongodb:
        condition: service_healthy
      user-redis:
        condition: service_healthy
    networks:
      - api-gateway
      - user-internal

  user-mongodb:
    image: mongo:8.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SRV_USER_MONGO_ROOT_USERNAME?}
      MONGO_INITDB_ROOT_PASSWORD: ${SRV_USER_MONGO_ROOT_PASSWORD?}
      MONGO_INITDB_DATABASE: ${SRV_USER_MONGO_DATABASE?}
      SRV_USER_MONGO_USERNAME: ${SRV_USER_MONGO_USERNAME?}
      SRV_USER_MONGO_PASSWORD: ${SRV_USER_MONGO_PASSWORD?}
    healthcheck:
      # healthcheck uses username and password value from user-mongodb environment variables defined above
      test:
        [
          "CMD-SHELL",
          "mongosh --norc --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.runCommand({ ping: 1 })'",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - user-mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - user-internal

  user-redis:
    image: redis:8-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - user-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - user-internal

networks:
  # Connects to Traefik
  api-gateway:
    name: spotlite-api-gateway
  # Creates a private network for this microservice
  user-internal:

volumes:
  user-mongo-data:
  user-redis-data:
