name: Build and Test Go Services

on:
  push:
    branches: [stable, develop]
  pull_request:

env:
  GO_VERSION: "1.25.5"

# Cancel the in-progress workflow when PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - common-lib
          - user-service
          - content-service
          - notification-service
          - subscription-service
          # - rating-service
          # - recommendation-service
          # - analytics-service
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.7
          working-directory: ${{ matrix.service }}

      - name: go mod tidy
        run: |
          go mod tidy -v
          git diff --exit-code go.mod go.sum
